import Head from 'next/head';
import Image from 'next/image';
import styled from '@emotion/styled';

const data = [
  { pokeName: 'Dude', number: '#001', type: 'water' },
  { pokeName: 'Pika', number: '#052', type: 'electric' },
  { pokeName: 'bulbazor', number: '#031', type: 'plant' },
];

const PokeContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  align-items: space-between;
  justify-content: center;
  margin: 0 auto;
  max-width: 1200px;
`;

const PokeCard = styled.div`
  background-color: #eee;
  border-radius: 10px;
  box-shadow: 0 3px 15px rgba(100, 100, 100, 0.5);
  margin: 10px;
  padding: 20px;
`;
const Title = styled.h1`
  letter-spacing: 3px;
`;
const CardImgContainer = styled.div`
  background-color: rgba(255, 255, 255, 0.6);
  border-radius: 50%;
  width: 120px;
  height: 120px;
  text-align: center;
  & {
    max-width: 90%;
    margin-top: 20px;
  }
`;
const CardInfo = styled.div``;
const CardNumber = styled.span``;
const CardSubtitle = styled.h3``;

const CardPokeType = styled.small``;

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <Title>Pokedex</Title>
        <PokeContainer>
          {data &&
            data.map(({ pokeName, number, type }) => {
              return (
                <>
                  <PokeCard>
                    <CardImgContainer>
                      <Image
                        alt="avatar"
                        height={400}
                        width={400}
                        src={
                          'https://avatarfiles.alphacoders.com/252/252088.jpg'
                        }></Image>
                      <CardInfo>
                        <CardNumber>{pokeName}</CardNumber>
                        <CardSubtitle>{number}</CardSubtitle>
                        <CardPokeType>{type}</CardPokeType>
                      </CardInfo>
                    </CardImgContainer>
                  </PokeCard>
                </>
              );
            })}
        </PokeContainer>
      </body>
    </>
  );
}
